spring:
  datasource:
    url: jdbc:h2:mem:warhammer
    username: user
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
#  liquibase:
#    change-log: classpath:db/master.xml
#    contexts: dev trzeba dodac conext="dev" w  include plik1.xml + master.xml
#    enabled: true
#    drop-first: false
#    default-schema: public