spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warhammer?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
#  liquibase:
#    contexts: prod