spring:
  datasource:
    url: jdbc:h2:mem:warhammer
    username: user
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    ddl-auto: create-drop
  liquibase:
    change-log: classpath:db/master.xml
    contexts: all
#http://localhost:8080/h2-console/login.do?jsessionid=7ae7800c86865d07d0c852082eaba78a

